# Generated by Django 5.0.6 on 2024-06-22 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Title',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Name',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='BookingDate',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='No_of_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='BookingDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='No_of_guests',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='menu',
            name='Inventory',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menu',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ID',
            field=models.DecimalField(decimal_places=0, max_digits=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ID',
            field=models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False),
        ),
    ]
